/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/flashcards/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Flashcards */
    post: operations["generate_flashcards_api_flashcards_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Flashcard */
    Flashcard: {
      /** Answer */
      answer: string;
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: "easy" | "medium" | "hard";
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Question */
      question: string;
      source: components["schemas"]["FlashcardSourceReference"];
    };
    /** FlashcardSourceInput */
    FlashcardSourceInput: {
      /** Highlight Boxes */
      highlight_boxes: components["schemas"]["HighlightBox"][];
      /** Note Text */
      note_text: string;
      /** Region Id */
      region_id: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Slide Number */
      slide_number: number;
      /** Slide Text */
      slide_text: string;
    };
    /** FlashcardSourceReference */
    FlashcardSourceReference: {
      /** Highlight Boxes */
      highlight_boxes: components["schemas"]["HighlightBox"][];
      /** Region Id */
      region_id: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Slide Number */
      slide_number: number;
      /** Slide Text */
      slide_text: string;
    };
    /** GenerateFlashcardsRequest */
    GenerateFlashcardsRequest: {
      /**
       * Count
       * @default 5
       */
      count?: number;
      source: components["schemas"]["FlashcardSourceInput"];
    };
    /** GenerateFlashcardsResponse */
    GenerateFlashcardsResponse: {
      /** Flashcards */
      flashcards: components["schemas"]["Flashcard"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Service
       * @constant
       */
      service: "traceback-api";
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** HighlightBox */
    HighlightBox: {
      /** Height */
      height: number;
      /** Width */
      width: number;
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  generate_flashcards_api_flashcards_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateFlashcardsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerateFlashcardsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
